In [1]:
%load_ext autotime
import geopandas as gpd
import pandas as pd
import numpy as np
from scipy.spatial import KDTree
from tqdm.auto import tqdm
from glob import glob
from shapely.geometry import LineString, Point
import folium
import json
pd.set_option('display.max_columns', None)

In [2]:
new_shorelines = gpd.GeoDataFrame.from_features([
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.270292,-46.510798],[168.256817,-46.516469],[168.244371,-46.514874]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[169.141324,-46.630181],[169.136646,-46.627808],[169.134758,-46.624802]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.029966,-46.353622],[168.023186,-46.35771],[168.02207,-46.357887],[168.012543,-46.354866],[168.011642,-46.353652],[168.019023,-46.345061]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.022842,-46.359694],[168.021083,-46.366742],[168.030953,-46.373405],[168.032112,-46.378971],[168.037434,-46.381991]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.131633,-46.872221],[168.130302,-46.871781],[168.125796,-46.875448],[168.127599,-46.879848],[168.132191,-46.881931]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.139358,-46.889616],[168.138371,-46.888838],[168.135538,-46.889454]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.133199,-46.890026],
    [168.13144,-46.892314]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.128865,-46.897123],[168.128994,-46.89856],[168.131247,-46.900158],[168.133864,-46.900591]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.138714,-46.899601],[168.140548,-46.900078],[168.142641,-46.898831]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[168.143821,-46.90224],[168.143928,-46.909013]]}},
    {"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[167.765522,-46.884718],[167.767239,-46.918145],[167.734623,-46.958699],[167.679005,-46.965494]]}}
])
new_shorelines.crs = 4326
new_shorelines

                                             geometry
0   LINESTRING (168.27029 -46.5108, 168.25682 -46....
1   LINESTRING (169.14132 -46.63018, 169.13665 -46...
2   LINESTRING (168.02997 -46.35362, 168.02319 -46...
3   LINESTRING (168.02284 -46.35969, 168.02108 -46...
4   LINESTRING (168.13163 -46.87222, 168.1303 -46....
5   LINESTRING (168.13936 -46.88962, 168.13837 -46...
6   LINESTRING (168.1332 -46.89003, 168.13144 -46....
7   LINESTRING (168.12886 -46.89712, 168.12899 -46...
8   LINESTRING (168.13871 -46.8996, 168.14055 -46....
9   LINESTRING (168.14382 -46.90224, 168.14393 -46...
10  LINESTRING (167.76552 -46.88472, 167.76724 -46...

In [3]:
m = new_shorelines.explore(tiles="ESRI.WorldImagery")
gpd.GeoSeries(new_shorelines.geometry.apply(lambda line: Point(line.coords[0])), crs=new_shorelines.crs).explore(m=m, color="red", name="transect start")
m

In [4]:
shorelines = gpd.read_file("shorelines.geojson")
transects = gpd.read_file("transects_extended.geojson")
poly = gpd.read_file("polygons.geojson")

In [5]:
nz_shorelines = shorelines[shorelines.id.str.startswith("nzd")]
latest_siteid = nz_shorelines.id.max()
latest_siteid_int = int(latest_siteid[4:])
new_siteids = new_shorelines.index.to_series().apply(lambda i: f"nzd0{latest_siteid_int + i + 1}")
print(f"Latest siteid is {latest_siteid}, so the new sites will be {new_siteids}")
new_shorelines["id"] = new_siteids
new_shorelines

Latest siteid is nzd0581, so the new sites will be 0     nzd0582
1     nzd0583
2     nzd0584
3     nzd0585
4     nzd0586
5     nzd0587
6     nzd0588
7     nzd0589
8     nzd0590
9     nzd0591
10    nzd0592
dtype: object

                                             geometry       id
0   LINESTRING (168.27029 -46.5108, 168.25682 -46....  nzd0582
1   LINESTRING (169.14132 -46.63018, 169.13665 -46...  nzd0583
2   LINESTRING (168.02997 -46.35362, 168.02319 -46...  nzd0584
3   LINESTRING (168.02284 -46.35969, 168.02108 -46...  nzd0585
4   LINESTRING (168.13163 -46.87222, 168.1303 -46....  nzd0586
5   LINESTRING (168.13936 -46.88962, 168.13837 -46...  nzd0587
6   LINESTRING (168.1332 -46.89003, 168.13144 -46....  nzd0588
7   LINESTRING (168.12886 -46.89712, 168.12899 -46...  nzd0589
8   LINESTRING (168.13871 -46.8996, 168.14055 -46....  nzd0590
9   LINESTRING (168.14382 -46.90224, 168.14393 -46...  nzd0591
10  LINESTRING (167.76552 -46.88472, 167.76724 -46...  nzd0592

In [6]:
pd.concat((shorelines, new_shorelines)).to_file("shorelines.geojson", driver="GeoJSON")

In [7]:
new_polys = gpd.GeoDataFrame({"id": new_siteids}, geometry=new_shorelines.to_crs(2193).buffer(100).minimum_rotated_rectangle().to_crs(4326), crs=4326)
new_polys.explore()

In [8]:
pd.concat((poly, new_polys)).to_file("polygons.geojson", driver="GeoJSON")

In [9]:
nz_transects = transects[transects.id.str.startswith("nzd")].to_crs(2193)
nz_transects

,id,site_id,orientation,along_dist,along_dist_norm,beach_slope,cil,ciu,trend,n_points,n_points_nonan,r2_score,mae,mse,rmse,intercept,ERODIBILITY,geometry
95050,nzd0001-0000,nzd0001,359.037136,3197.737936,1.000000,0.110,0.0681,0.2000,-0.174010,196.0,192.0,0.003917,17.659820,458.983904,21.423910,325.937325,None,"LINESTRING (1596662.375 6190263.089, 1596646.6..."
95051,nzd0001-0001,nzd0001,359.037136,3097.737936,0.968728,0.115,0.0738,0.2000,-0.181775,196.0,193.0,0.005612,15.338270,353.476544,18.800972,328.697573,None,"LINESTRING (1596744.903 6190264.499, 1596729.1..."
95052,nzd0001-0002,nzd0001,359.037136,2997.737936,0.937456,0.120,0.0770,0.2000,-0.306998,196.0,193.0,0.019757,14.242079,282.327917,16.802616,334.822195,None,"LINESTRING (1596827.431 6190265.908, 1596811.6..."
95053,nzd0001-0003,nzd0001,359.037136,2897.737936,0.906184,0.065,0.0546,0.0759,-0.344997,196.0,194.0,0.032463,12.443181,217.289816,14.740754,344.022130,None,"LINESTRING (1596909.959 6190267.317, 1596894.2..."
95054,nzd0001-0004,nzd0001,359.037136,2797.737936,0.874912,0.065,0.0568,0.0788,-0.418404,196.0,194.0,0.052214,11.504372,194.647497,13.951613,356.546817,None,"LINESTRING (1596992.486 6190268.724, 1596976.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147491,nzd0581-0000,nzd0581,NaN,NaN,NaN,0.180,0.0821,0.2000,-0.184513,621.0,621.0,0.002403,19.936131,816.440687,28.573426,196.335405,None,"LINESTRING (1574800.891 5169242.469, 1574503.2..."
147492,nzd0581-0001,nzd0581,NaN,NaN,NaN,0.035,0.0260,0.0453,-0.532678,621.0,616.0,0.090244,7.911744,165.004271,12.845399,219.908703,None,"LINESTRING (1574854.346 5169182.903, 1574556.6..."
147493,nzd0581-0002,nzd0581,NaN,NaN,NaN,0.030,0.0250,0.0335,-0.348804,621.0,619.0,0.125428,5.667830,48.825130,6.987498,223.793487,None,"LINESTRING (1574907.778 5169123.363, 1574610.0..."
147494,nzd0581-0003,nzd0581,NaN,NaN,NaN,0.030,0.0247,0.0330,0.498811,621.0,618.0,0.068427,10.256004,195.243229,13.972946,201.023380,None,"LINESTRING (1574961.187 5169063.849, 1574663.5..."
147495,nzd0581-0004,nzd0581,NaN,NaN,NaN,0.025,0.0237,0.0280,-0.198781,621.0,604.0,0.003397,21.050041,659.910009,25.688714,194.500018,None,"LINESTRING (1575014.619 5169004.309, 1574716.9..."

In [15]:
def create_transects(line, spacing=80, transect_length=400):
    transects = []
    distances = np.arange(0, line.length, spacing)

    for distance in distances:
        # Find point along the average line
        point = line.interpolate(distance)
        
        # Find the direction of the line at this point (tangent direction)
        nearest_point_ahead = line.interpolate(min(distance + 1e-6, line.length))
        direction = np.arctan2(nearest_point_ahead.y - point.y, nearest_point_ahead.x - point.x)
        
        # Rotate 90 degrees (perpendicular) and extend to create a transect
        transect = LineString([
            Point(
                point.x - transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y - transect_length / 2 * np.sin(direction + np.pi / 2)
            ),
            Point(
                point.x + transect_length / 2 * np.cos(direction + np.pi / 2),
                point.y + transect_length / 2 * np.sin(direction + np.pi / 2)
            )
        ])
        
        transects.append(transect)
    
    transects = gpd.GeoDataFrame(geometry=transects, crs=2193).to_crs(4326)
    return transects

all_new_transects = []
for new_shoreline in new_shorelines.to_crs(2193).itertuples():
    new_transects = create_transects(new_shoreline.geometry)
    new_transects["id"] = new_shoreline.id + "-" + new_transects.index.astype(str).str.pad(4, fillchar="0")
    new_transects["site_id"] = new_shoreline.id
    all_new_transects.append(new_transects)

all_new_transects = gpd.GeoDataFrame(pd.concat(all_new_transects).reset_index(drop=True), crs=4326)
display(all_new_transects)
m = all_new_transects.explore(tiles="ESRI.WorldImagery")
new_shorelines.explore(m=m)
new_polys.boundary.explore(m=m)
sites_to_flip = ["nzd0582", "nzd0583", "nzd0592"]
for site_id in sites_to_flip:
    mask = all_new_transects.site_id == site_id
    all_new_transects.loc[mask, "geometry"] = all_new_transects.loc[mask].geometry.apply(lambda line: LineString(line.coords[::-1]))
gpd.GeoSeries(all_new_transects.geometry.apply(lambda line: Point(line.coords[0])), crs=all_new_transects.crs).explore(m=m, color="red", name="transect start")
print("Make sure the origin is inland")
m

                                              geometry            id  site_id
0    LINESTRING (168.26894 -46.50926, 168.27165 -46...  nzd0582-0000  nzd0582
1    LINESTRING (168.26805 -46.50964, 168.27076 -46...  nzd0582-0001  nzd0582
2    LINESTRING (168.26716 -46.51001, 168.26987 -46...  nzd0582-0002  nzd0582
3    LINESTRING (168.26627 -46.51039, 168.26898 -46...  nzd0582-0003  nzd0582
4    LINESTRING (168.26538 -46.51076, 168.26809 -46...  nzd0582-0004  nzd0582
..                                                 ...           ...      ...
325  LINESTRING (167.68353 -46.96312, 167.68445 -46...  nzd0592-0160  nzd0592
326  LINESTRING (167.6825 -46.96324, 167.68342 -46....  nzd0592-0161  nzd0592
327  LINESTRING (167.68146 -46.96337, 167.68239 -46...  nzd0592-0162  nzd0592
328  LINESTRING (167.68043 -46.9635, 167.68135 -46....  nzd0592-0163  nzd0592
329  LINESTRING (167.6794 -46.96362, 167.68032 -46....  nzd0592-0164  nzd0592

[330 rows x 3 columns]

Make sure the origin is inland

In [16]:
pd.concat((transects, all_new_transects)).to_file("transects_extended.geojson", driver="GeoJSON")