In [1]:
%load_ext autotime
import geopandas as gpd
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
from tqdm.contrib.concurrent import process_map
from glob import glob
from shapely.geometry import LineString, Point
import folium
import matplotlib.pyplot as plt
import pytz
from datetime import datetime, timedelta
pd.set_option('display.max_columns', None)
import SDS_slope

In [2]:
transects = gpd.read_file("transects_extended.geojson").set_index("id")
transects

,site_id,orientation,along_dist,along_dist_norm,beach_slope,cil,ciu,trend,n_points,n_points_nonan,r2_score,mae,mse,rmse,intercept,ERODIBILITY,geometry
id,,,,,,,,,,,,,,,,,
aus0001-0000,aus0001,104.347648,0.000000,0.000000,0.085,0.0545,0.2000,-1.441081,767.0,428.0,0.168420,28.102591,1263.560863,35.546601,179.085729,None,"LINESTRING (153.26555 -24.7007, 153.26938 -24...."
aus0001-0001,aus0001,93.495734,98.408334,0.002935,0.050,0.0387,0.0640,-1.037105,767.0,569.0,0.097874,25.419324,1033.770813,32.152306,212.247788,None,"LINESTRING (153.26525 -24.7019, 153.2692 -24.7..."
aus0001-0002,aus0001,82.069341,198.408334,0.005918,0.050,0.0428,0.0647,-0.680019,767.0,588.0,0.053927,22.632907,838.007507,28.948359,205.106151,None,"LINESTRING (153.26539 -24.70316, 153.26931 -24..."
aus0001-0003,aus0001,81.192757,298.402523,0.008900,0.055,0.0480,0.0659,-0.405198,767.0,598.0,0.023412,20.749758,698.653187,26.432048,191.745881,None,"LINESTRING (153.26555 -24.70408, 153.26945 -24..."
aus0001-0004,aus0001,81.065473,398.402523,0.011882,0.075,0.0614,0.0922,-0.090025,767.0,608.0,0.001277,19.889328,655.810616,25.608800,175.092121,None,"LINESTRING (153.2657 -24.70497, 153.26961 -24...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nzd0604-0006,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17153 -36.94882, 175.1696 -36...."
nzd0604-0007,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17234 -36.94851, 175.17041 -36..."
nzd0604-0008,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17356 -36.94778, 175.17058 -36..."
nzd0604-0009,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.1747 -36.9462, 175.1703 -36.94..."
nzd0604-0010,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17484 -36.94532, 175.17038 -36..."

In [3]:
new_transects = transects[
    transects.index.str.startswith("nzd") & transects.beach_slope.isna()
]
new_transects

,site_id,orientation,along_dist,along_dist_norm,beach_slope,cil,ciu,trend,n_points,n_points_nonan,r2_score,mae,mse,rmse,intercept,ERODIBILITY,geometry
id,,,,,,,,,,,,,,,,,
nzd0603-0000,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15027 -36.94897, 175.1535 -36...."
nzd0603-0001,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.1509 -36.94949, 175.15412 -36...."
nzd0603-0002,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15197 -36.95025, 175.15435 -36..."
nzd0603-0003,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15273 -36.95064, 175.15511 -36..."
nzd0603-0004,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15349 -36.95102, 175.15587 -36..."
nzd0603-0005,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15456 -36.95152, 175.15634 -36..."
nzd0603-0006,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15538 -36.9518, 175.15717 -36...."
nzd0603-0007,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15621 -36.95209, 175.15799 -36..."
nzd0603-0008,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15778 -36.9524, 175.15814 -36...."
nzd0603-0009,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15867 -36.95246, 175.15904 -36..."
nzd0603-0010,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.15957 -36.95252, 175.15993 -36..."
nzd0603-0011,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16046 -36.95258, 175.16083 -36..."
nzd0603-0012,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16212 -36.95233, 175.1609 -36...."
nzd0603-0013,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16298 -36.95213, 175.16177 -36..."
nzd0603-0014,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16442 -36.95148, 175.16182 -36..."
nzd0603-0015,nzd0603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16516 -36.95106, 175.16255 -36..."
nzd0604-0000,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16478 -36.94975, 175.16614 -36..."
nzd0604-0001,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16639 -36.95001, 175.16626 -36..."
nzd0604-0002,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16746 -36.94995, 175.16699 -36..."
nzd0604-0003,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16835 -36.94988, 175.16788 -36..."
nzd0604-0004,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.16987 -36.94944, 175.168 -36.9..."
nzd0604-0005,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17069 -36.94914, 175.16882 -36..."
nzd0604-0006,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17153 -36.94882, 175.1696 -36...."
nzd0604-0007,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17234 -36.94851, 175.17041 -36..."
nzd0604-0008,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17356 -36.94778, 175.17058 -36..."
nzd0604-0009,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.1747 -36.9462, 175.1703 -36.94..."
nzd0604-0010,nzd0604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"LINESTRING (175.17484 -36.94532, 175.17038 -36..."

In [4]:
plt.ioff()


def estimate_slopes(site_id):
    df = pd.read_csv(f"data/{site_id}/transect_time_series.csv")
    df.index = pd.to_datetime(df.dates)
    df.drop(columns=["dates", "satname"], inplace=True)
    tides = pd.read_csv(f"data/{site_id}/tides.csv")
    tides.dates = pd.to_datetime(tides.dates)
    tides.set_index("dates", inplace=True)
    assert all(pd.to_datetime(df.index).round("10min") == tides.index)
    # slope estimation settings
    days_in_year = 365.2425
    seconds_in_day = 24 * 3600
    settings_slope = {
        "slope_min": 0.01,  # minimum slope to trial
        "slope_max": 0.2,  # maximum slope to trial
        "delta_slope": 0.005,  # slope increment
        "date_range": [1999, 2020],  # range of dates over which to perform the analysis
        "n_days": 8,  # sampling period [days]
        "n0": 50,  # parameter for Nyquist criterium in Lomb-Scargle transforms
        "freqs_cutoff": 1.0 / (seconds_in_day * 30),  # 1 month frequency
        "delta_f": 100 * 1e-10,  # deltaf for identifying peak tidal frequency band
        "prc_conf": 0.05,  # percentage above minimum to define confidence bands in energy curve
    }
    settings_slope["date_range"] = [
        pytz.utc.localize(datetime(settings_slope["date_range"][0], 5, 1)),
        pytz.utc.localize(datetime(settings_slope["date_range"][1], 1, 1)),
    ]
    beach_slopes = SDS_slope.range_slopes(
        settings_slope["slope_min"],
        settings_slope["slope_max"],
        settings_slope["delta_slope"],
    )

    # find tidal peak frequency (can choose 7 or 8 in this case)
    settings_slope["n_days"] = 7
    settings_slope["freqs_max"] = SDS_slope.find_tide_peak(
        df.index, tides.tide, settings_slope
    )
    # estimate beach-face slopes along the transects
    slope_est, cis = dict([]), dict([])
    for key in df.keys():
        # remove NaNs
        idx_nan = np.isnan(df[key])
        dates = [df.index[_] for _ in np.where(~idx_nan)[0]]
        if len(dates) == 0:
            print(f"No data for {site_id} transect {key}, skipping.")
            continue
        tide = tides.tide.to_numpy()[~idx_nan]
        composite = df[key][~idx_nan]
        # apply tidal correction
        tsall = SDS_slope.tide_correct(composite, tide, beach_slopes)
        title = "Transect %s" % key
        # SDS_slope.plot_spectrum_all(dates,composite,tsall,settings_slope, title)
        try:
            slope_est[key], cis[key] = SDS_slope.integrate_power_spectrum(
                dates, tsall, settings_slope
            )
        except Exception as e:
            print(f"Error estimating slope for {site_id} transect {key}: {e}")
            continue
        # print('Beach slope at transect %s: %.3f'%(key, slope_est[key]))
    return pd.DataFrame(
        {
            "beach_slope": slope_est,
            "cil": {k: v[0] for k, v in cis.items()},
            "ciu": {k: v[1] for k, v in cis.items()},
        },
        index=slope_est.keys(),
    )


new_slopes = process_map(estimate_slopes, new_transects.site_id.unique())
# estimate_slopes("nzd0563")

  0%|          | 0/2 [00:00<?, ?it/s]

In [5]:
(pd.concat(new_slopes).beach_slope - transects.beach_slope).describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: beach_slope, dtype: float64

In [6]:
np.rad2deg(np.arctan(0.01))

0.5729386976834859

In [7]:
transects.update(pd.concat(new_slopes))
transects.to_file("transects_extended.geojson")